// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AloneVersionning","status":true,"description":"","parameters":{}},
{"name":"Scene_SplashScreen","status":true,"description":"","parameters":{}},
{"name":"Rhyme_MapSmoothScrolling","status":true,"description":"this plugin permit to smooth scroll in map","parameters":{"SpeedDivider":"8"}}
];
